# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
 extract_email:
   runs-on: ubuntu-latest
   steps:
         - uses: actions/checkout@v3

         - name: Extract email from changed files
           run: |
            # Get the pull request diff URL from the issue payload
            diff_url=$(jq -r '.issue.pull_request.diff_url' $GITHUB_EVENT_PATH)

            # Download the diff and extract the added lines with email headers
            added_lines=$(curl -sSL "$diff_url" | awk '/^+.*email:/i' | awk '{print $2}')

            # Print the email values to the console
            echo "$added_lines"
