# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
 issues:
   types: [opened , edited]
 
jobs:
 extract_email:
   runs-on: ubuntu-latest
   
   steps:
         - uses: actions/checkout@v3

         - name: Extract email from changed files
           id: email
           run: |
               pr_number=$(jq -r '.issue.pull_request.number' $GITHUB_EVENT_PATH)
               echo "::set-output name=pr_number::$pr_number"
         - name: print email
           run : |
                echo ${{steps.email.outputs.pr_number}}
            
            
            
