# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
 issues:
   types: [opened]
 
jobs:
 extract_email:
   runs-on: ubuntu-latest
   
   steps:
         - uses: actions/checkout@v3

         - name: Extract email from changed files
           run: |
            # Get the pull request diff URL from the issue payload'
            pr_number=$(jq -r '.issue.pull_request.number' $GITHUB_EVENT_PATH)
            
